### ISSUE TITLE
Arguments not working

### ISSUE THREAD

**Issue by ghost** [nikitavoloboev/alfred-ask-create-share#1]
`w:` doesn't bring anything up, even when adding `new codepen`. 

![screenshot2016-12-14 20 27 09](https://cloud.githubusercontent.com/assets/7698292/21208410/c77de968-c23b-11e6-8499-ed7f054b7242.jpeg)

**Comment by nikivdev** [comment]
You are searching in alfred itself and not in the list filter. In order to search in the lister filter, assign some hotkey to it and attach it like I do here : 


![2016-12-15 at 02 38](https://cloud.githubusercontent.com/assets/6391776/21208648/8f4cac4e-c26f-11e6-892a-1ecd607ddfae.png)

or add a keyword trigger :

![2016-12-15 at 02 38](https://cloud.githubusercontent.com/assets/6391776/21208655/9a172794-c26f-11e6-9774-fadf83babf6f.png)
